author: Move Upwards
author_url: https://github.com/MoveUpwards
github_url: https://github.com/MoveUpwards/Nevanlinna
root_url: https://github.com/MoveUpwards
module: Nevanlinna
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, 'Nevanlinna.xcworkspace', -scheme, 'Nevanlinna iOS']